---

- name: install Python dependencies
  apt: pkg={{ item }}  state=present
  with_items:
    - g++
    - make
    - libxslt-dev     # for python lxml package
    - python3
    - python3-pip
    - python3-dev
    - python3-setuptools
    - python3-pycurl
    # pillow dependencies
    - libjpeg-dev
    - libtiff4-dev
    - zlib1g-dev
    - libfreetype6-dev
    - liblcms2-dev
    - libwebp-dev
    - tcl8.5-dev
    - tk8.5-dev

- name: Install global python packages
  pip: name="{{python_global_packages|join(' ')}}" executable=/usr/bin/pip3
  when: python_install
