---
#
# Creates and manages a Jenkins CI server running on a Ubuntu Vagrant VM
#
- hosts: all
  roles:
    - common-packages
    - email-sendgrid
    - ANXS.postgresql
    - python3-ubuntu-repository
    - geerlingguy.jenkins
    - cron
