---

- name: some useful development aliases
  lineinfile: dest={{ admin_user.home }}/.bash_aliases state=present create=yes line='{{ item }}'
  with_items:
    - 'alias djrun="cd /vagrant;./manage.py runserver 0.0.0.0:8000"'
    - 'alias djrun+="cd /vagrant;./manage.py runserver_plus 0.0.0.0:8000"'

- name: devel pg_dump cron job
  cron: name='pg_dump' minute='*/20' job='pg_dump -U {{ postgresql_admin_user }} {{ db_name }} > {{ data_directory }}/{{ data_backup_file }}' user='{{ admin_user.id }}'
  when: postgresql_version is defined
  sudo: no

- name: populate database from db backup alias
  lineinfile: dest={{ admin_user.home }}/.bash_aliases state=present create=yes line='{{ item }}'
  with_items:
    - 'alias load-dev-db="psql -U {{ postgresql_admin_user }} -d {{ db_name }} < {{ data_directory }}/{{ data_backup_file }}"'
  when: postgresql_version is defined
